apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-test
  template:
    metadata:
      labels:
        app: laravel-test
    spec:
      containers:
        - name: laravel-test
          image: 257101242541.dkr.ecr.us-east-1.amazonaws.com/laravel-test:development
          ports:
            - containerPort: 8000
              name: http-port
              protocol: TCP
