apiVersion: v1
kind: Service
metadata:
  name: laravel-test
  namespace: development
  labels:
    name: laravel-test
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8000
      protocol: TCP
      name: https
  selector:
    name: laravel-test
